pipeline:
  identifier: Build_wowitsbala_wowitsbala_1754938815528
  name: Build wowitsbala
  orgIdentifier: default
  projectIdentifier: SonarQube
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1750965264531
        repoName: wowitsbala/wowitsbala
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
